name: redmanmale
email: redmanmale@gmail.com
description: if-goto
baseurl: ""
url: "https://redmanmale.github.io"
github_username: redmanmale
avatar: "https://avatars0.githubusercontent.com/u/6782721"

markdown: kramdown
highlighter: rouge
permalink: pretty
encoding: utf-8

footer-links:
    github: redmanmale
    habrahabr: redmanmale
    email: redmanmale@gmail.com
    rss: RSS
    telegram: world_in_red

sass:
    style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
